### PR TITLE
Updated message/about/infos layout

### PR DESCRIPTION
**Pull request by s-faychatelard**
I used constraints on the message center part to be correct on different screen sizes. I've changed the message (dev/user) to be placed and sized correctly.

Here is a series of shots representing the changes (Don't take the bar colors in consideration, I've not pushed those changes) :

https://www.dviance.net/content/PR/1.jpg
https://www.dviance.net/content/PR/2.jpg
https://www.dviance.net/content/PR/3.jpg
https://www.dviance.net/content/PR/4.jpg
https://www.dviance.net/content/PR/5.jpg

### CODE REVIEW

**Comment by s-faychatelard** [comment]
This pull request also remove the iOS 5 compatibility

**Comment by pkamb** [comment]
Hi, thanks for the PR. Could you please fill out the description to let us know your intentions with these modifications and what has changed? Is there a problem you are trying to fix? Perhaps some screenshots as well. Thanks!

**Comment by s-faychatelard** [comment]
NP, edited

**Comment by pkamb** [comment]
@s-faychatelard private screenshots :)

**Comment by s-faychatelard** [comment]
Not private but due to a bug on Safari which reroot to https automatically you must use Chrome ;)

**Comment by pkamb** [comment]
Hmm, Chrome is redirecting to `https` automatically for me.

**Comment by s-faychatelard** [comment]
Greaaat let me change that URLs -> Go back to the top

**Comment by pkamb** [comment]
Inline:

Imgur
Imgur
Imgur
Imgur
Imgur

**Comment by s-faychatelard** [comment]
Didn't know that was possible! haha

**Pull request closed without merging**
